// .env에서 먼저 읽고 사용하는 객체 선언
// Next.js는 빌드 시 .env 파일의 값을 process.env에 자동 주입한다.
const readEnv = (name: string, fallback: string) => {
  const value = process.env[name]?.trim();
  return value && value.length > 0 ? value : fallback;
};

const DEFAULT_SITE_URL = "https://www.tdch.co.kr";
const DEFAULT_SITE_NAME = "The 제자교회";
const DEFAULT_SITE_ALTERNATE_NAME = "더제자교회";
const DEFAULT_SITE_TAGLINE = "성령으로 제자삼는 교회";
const DEFAULT_CHURCH_ADDRESS = "경기도 수원시 팔달구 경수대로425 지하1층(나인아트홀)";
const DEFAULT_CHURCH_ADDRESS_STREET = "경수대로425 지하1층(나인아트홀)";
const DEFAULT_CHURCH_ADDRESS_LOCALITY = "수원시";
const DEFAULT_CHURCH_ADDRESS_REGION = "경기도";
const DEFAULT_CHURCH_POSTAL_CODE = "16490";
const DEFAULT_CHURCH_COUNTRY = "KR";
const DEFAULT_CHURCH_PHONE = "010-5252-8580";
const DEFAULT_CHURCH_EMAIL = "timothy35@hanmail.net";
const DEFAULT_YOUTUBE_URL =
  "https://www.youtube.com/@%EB%8D%94%EC%A0%9C%EC%9E%90%EA%B5%90%ED%9A%8C";
const DEFAULT_YOUTUBE_LABEL = "The 제자티비";
const DEFAULT_NAVER_MAP_URL =
  "https://map.naver.com/p/search/%EB%82%98%EC%9D%B8%EC%95%84%ED%8A%B8%ED%99%80/place/1394960485?c=15.00,0,0,0,dh&placePath=/home?bk_query=%EB%82%98%EC%9D%B8%EC%95%84%ED%8A%B8%ED%99%80&entry=bmp&from=map&fromPanelNum=2&timestamp=202603021305&locale=ko&svcName=map_pcv5&searchText=%EB%82%98%EC%9D%B8%EC%95%84%ED%8A%B8%ED%99%80";
const DEFAULT_KAKAO_MAP_URL =
  "https://map.kakao.com/link/search/%EA%B2%BD%EA%B8%B0%EB%8F%84%20%EC%88%98%EC%9B%90%EC%8B%9C%20%ED%8C%94%EB%8B%AC%EA%B5%AC%20%EA%B2%BD%EC%88%98%EB%8C%80%EB%A1%9C425%20%EB%82%98%EC%9D%B8%EC%95%84%ED%8A%B8%ED%99%80";
const DEFAULT_NAVER_MAP_PUBLIC_CLIENT_ID = "dzevj9klz8";
const DEFAULT_CHURCH_LATITUDE = "37.2642526267482";
const DEFAULT_CHURCH_LONGITUDE = "127.025125618372";
const DEFAULT_GIVING_BANK = "하나은행 181-04-01160-381 예금주:이진욱(The제자교회)";
const DEFAULT_GIVING_OWNER = "이진욱(The제자교회)";
const DEFAULT_NEWCOMER_CONTACT_DEPARTMENT = "교육부";
const DEFAULT_NEWCOMER_APPLY_TEXT = "홈페이지 또는 주일 안내데스크";
const DEFAULT_PUBLIC_API_BASE_URL = "http://localhost:8080";

export const SITE_URL = readEnv("NEXT_PUBLIC_SITE_URL", DEFAULT_SITE_URL);
export const SITE_NAME = readEnv("NEXT_PUBLIC_SITE_NAME", DEFAULT_SITE_NAME);
export const SITE_ALTERNATE_NAME = readEnv(
  "NEXT_PUBLIC_SITE_ALTERNATE_NAME",
  DEFAULT_SITE_ALTERNATE_NAME,
);
export const SITE_TAGLINE = readEnv("NEXT_PUBLIC_SITE_TAGLINE", DEFAULT_SITE_TAGLINE);
export const SITE_TITLE = `${SITE_NAME} — ${SITE_TAGLINE}`;

export const CHURCH_ADDRESS = readEnv("NEXT_PUBLIC_CHURCH_ADDRESS", DEFAULT_CHURCH_ADDRESS);
export const CHURCH_ADDRESS_STREET = readEnv(
  "NEXT_PUBLIC_CHURCH_ADDRESS_STREET",
  DEFAULT_CHURCH_ADDRESS_STREET,
);
export const CHURCH_ADDRESS_LOCALITY = readEnv(
  "NEXT_PUBLIC_CHURCH_ADDRESS_LOCALITY",
  DEFAULT_CHURCH_ADDRESS_LOCALITY,
);
export const CHURCH_ADDRESS_REGION = readEnv(
  "NEXT_PUBLIC_CHURCH_ADDRESS_REGION",
  DEFAULT_CHURCH_ADDRESS_REGION,
);
export const CHURCH_POSTAL_CODE = readEnv(
  "NEXT_PUBLIC_CHURCH_POSTAL_CODE",
  DEFAULT_CHURCH_POSTAL_CODE,
);
export const CHURCH_COUNTRY = readEnv(
  "NEXT_PUBLIC_CHURCH_COUNTRY",
  DEFAULT_CHURCH_COUNTRY,
);
export const CHURCH_PHONE = readEnv("NEXT_PUBLIC_CHURCH_PHONE", DEFAULT_CHURCH_PHONE);
export const CHURCH_EMAIL = readEnv("NEXT_PUBLIC_CHURCH_EMAIL", DEFAULT_CHURCH_EMAIL);
export const YOUTUBE_CHANNEL_URL = readEnv("NEXT_PUBLIC_YOUTUBE_URL", DEFAULT_YOUTUBE_URL);
export const YOUTUBE_CHANNEL_LABEL = readEnv(
  "NEXT_PUBLIC_YOUTUBE_LABEL",
  DEFAULT_YOUTUBE_LABEL,
);
export const NAVER_MAP_URL = readEnv("NEXT_PUBLIC_NAVER_MAP_URL", DEFAULT_NAVER_MAP_URL);
export const KAKAO_MAP_URL = readEnv("NEXT_PUBLIC_KAKAO_MAP_URL", DEFAULT_KAKAO_MAP_URL);
export const NAVER_MAP_PUBLIC_CLIENT_ID = readEnv(
  "NEXT_PUBLIC_NAVER_MAP_CLIENT_ID",
  DEFAULT_NAVER_MAP_PUBLIC_CLIENT_ID,
);
export const CHURCH_LATITUDE = readEnv("NEXT_PUBLIC_CHURCH_LAT", DEFAULT_CHURCH_LATITUDE);
export const CHURCH_LONGITUDE = readEnv("NEXT_PUBLIC_CHURCH_LNG", DEFAULT_CHURCH_LONGITUDE);
export const CHURCH_LATITUDE_NUMBER = Number(CHURCH_LATITUDE);
export const CHURCH_LONGITUDE_NUMBER = Number(CHURCH_LONGITUDE);
export const GIVING_BANK = readEnv("NEXT_PUBLIC_GIVING_BANK", DEFAULT_GIVING_BANK);
export const GIVING_OWNER = readEnv("NEXT_PUBLIC_GIVING_OWNER", DEFAULT_GIVING_OWNER);
export const NEWCOMER_CONTACT_DEPARTMENT = readEnv(
  "NEXT_PUBLIC_NEWCOMER_CONTACT_DEPARTMENT",
  DEFAULT_NEWCOMER_CONTACT_DEPARTMENT,
);
export const NEWCOMER_CONTACT_APPLY_TEXT = readEnv(
  "NEXT_PUBLIC_NEWCOMER_CONTACT_APPLY_TEXT",
  DEFAULT_NEWCOMER_APPLY_TEXT,
);
export const PUBLIC_API_BASE_URL = readEnv(
  "NEXT_PUBLIC_API_BASE_URL",
  DEFAULT_PUBLIC_API_BASE_URL,
);

export const SITE_DESCRIPTION = `${SITE_ALTERNATE_NAME}(${SITE_NAME})는 ${SITE_TAGLINE}를 비전으로 삼는 교회입니다. ${CHURCH_ADDRESS}`;
