import type {
  AttendanceWeek,
  FamilyMember,
  FaithProfile,
  Member,
  MemberEvent,
  ServiceAssignment,
  TrainingRecord,
} from "./types";

export const MOCK_MEMBERS: Member[] = [
  {
    id: "m-001",
    name: "김은혜",
    nameEn: "Kim Eunhye",
    baptismName: "안나",
    sex: "F",
    birthDate: "1981-06-14",
    birthCalendar: "SOLAR",
    phone: "010-2345-6789",
    emergencyPhone: "010-1111-2222",
    emergencyRelation: "배우자",
    email: "eunhye@example.com",
    address: "서울특별시 강남구 테헤란로 123",
    addressDetail: "101동 1502호 (역삼동, 역삼아파트)",
    job: "초등학교 교사",
    cellId: "c-1",
    cellLabel: "1구역 · 요한셀",
    status: "ACTIVE",
    faithStage: "DISCIPLE",
    office: "DEACON_TEMP",
    officeAppointedAt: "2021-01-03",
    registeredAt: "2018-03-11",
    memo: "주일학교 1학년 담당 교사. 찬양팀 피아노 가능. 새가족 심방 동행 가능한 자매.",
    avatarGrad: 1,
    initial: "김",
    faithStageSuggestion: "MINISTER",
    faithYears: 22,
    age: 45,
  },
  {
    id: "m-002",
    name: "박정민",
    sex: "M",
    birthDate: "1968-04-02",
    birthCalendar: "SOLAR",
    phone: "010-1234-5678",
    address: "서울 송파구 잠실동",
    cellId: "c-2",
    cellLabel: "2구역 · 바울셀",
    status: "ACTIVE",
    faithStage: "LEADER",
    office: "ELDER",
    officeAppointedAt: "2015-01-04",
    registeredAt: "1998-11-20",
    avatarGrad: 2,
    initial: "박",
    faithYears: 35,
    age: 58,
  },
  {
    id: "m-003",
    name: "이서연",
    sex: "F",
    birthDate: "1992-09-11",
    birthCalendar: "SOLAR",
    phone: "010-9876-5432",
    address: "서울 마포구 합정동",
    cellId: "c-3",
    cellLabel: "3구역 · 마가셀",
    status: "NEW",
    faithStage: "NEW_COMER",
    office: "LAY",
    registeredAt: "2026-03-02",
    avatarGrad: 3,
    initial: "이",
    faithYears: 1,
    age: 33,
  },
  {
    id: "m-004",
    name: "최준호",
    sex: "M",
    birthDate: "1975-12-08",
    birthCalendar: "SOLAR",
    phone: "010-5566-7788",
    address: "경기 성남시 분당구",
    cellId: "c-1",
    cellLabel: "1구역 · 요한셀",
    status: "ACTIVE",
    faithStage: "DISCIPLE",
    office: "DEACON",
    officeAppointedAt: "2018-01-07",
    registeredAt: "2010-05-02",
    avatarGrad: 4,
    initial: "최",
    faithYears: 25,
    age: 50,
  },
  {
    id: "m-005",
    name: "정미경",
    sex: "F",
    birthDate: "1962-01-22",
    birthCalendar: "LUNAR",
    phone: "010-3344-5566",
    address: "서울 노원구 상계동",
    cellId: "c-5",
    cellLabel: "5구역 · 베드로셀",
    status: "RESTING",
    statusSuggestion: "RESTING",
    faithStage: "MINISTER",
    office: "GWONSA",
    officeAppointedAt: "2010-01-03",
    registeredAt: "2005-09-18",
    avatarGrad: 5,
    initial: "정",
    faithYears: 30,
    age: 64,
  },
  {
    id: "m-006",
    name: "한지훈",
    sex: "M",
    birthDate: "1990-07-19",
    birthCalendar: "SOLAR",
    phone: "010-7788-9900",
    address: "서울 용산구 이태원동",
    cellId: "c-4",
    cellLabel: "4구역 · 누가셀",
    status: "ACTIVE",
    faithStage: "SETTLED",
    office: "LAY",
    registeredAt: "2024-01-14",
    avatarGrad: 6,
    initial: "한",
    faithYears: 2,
    age: 35,
  },
  {
    id: "m-007",
    name: "윤하늘",
    sex: "F",
    birthDate: "2011-03-22",
    birthCalendar: "SOLAR",
    phone: "010-1111-2222",
    address: "서울 강남구 역삼동",
    cellId: "c-1",
    cellLabel: "1구역 · 요한셀",
    status: "ACTIVE",
    faithStage: "NEW_COMER",
    office: "LAY",
    registeredAt: "2018-03-11",
    avatarGrad: 7,
    initial: "윤",
    faithYears: 8,
    age: 14,
  },
  {
    id: "m-008",
    name: "조태영",
    sex: "M",
    birthDate: "1948-08-15",
    birthCalendar: "SOLAR",
    phone: "010-2020-3030",
    address: "서울 송파구 석촌동",
    cellId: "c-2",
    cellLabel: "2구역 · 바울셀",
    status: "LONG_ABSENT",
    statusSuggestion: "LONG_ABSENT",
    faithStage: "LEADER",
    office: "ELDER_EMERITUS",
    officeAppointedAt: "1995-01-01",
    registeredAt: "1985-04-07",
    avatarGrad: 8,
    initial: "조",
    faithYears: 50,
    age: 77,
  },
  {
    id: "m-009",
    name: "송민서",
    sex: "F",
    birthDate: "1995-05-30",
    birthCalendar: "SOLAR",
    phone: "010-4321-8765",
    address: "서울 서초구 반포동",
    cellId: "c-3",
    cellLabel: "3구역 · 마가셀",
    status: "NEW",
    faithStage: "NEW_COMER",
    office: "LAY",
    registeredAt: "2026-04-06",
    avatarGrad: 3,
    initial: "송",
    faithYears: 0,
    age: 30,
  },
  {
    id: "m-010",
    name: "임도현",
    sex: "M",
    birthDate: "1985-11-04",
    birthCalendar: "SOLAR",
    phone: "010-6677-8899",
    address: "서울 양천구 목동",
    cellId: "c-4",
    cellLabel: "4구역 · 누가셀",
    status: "ACTIVE",
    faithStage: "GROWING",
    office: "LAY",
    registeredAt: "2020-08-23",
    avatarGrad: 5,
    initial: "임",
    faithYears: 6,
    age: 40,
  },
];

export const MOCK_FAITH_PROFILES: Record<string, FaithProfile> = {
  "m-001": {
    memberId: "m-001",
    confessDate: "2003-08-15",
    learningDate: "2003-12-21",
    baptismDate: "2004-06-06",
    baptismPlace: "더제자교회",
    baptismOfficiant: "김○○ 담임목사",
    ministryTags: ["교육", "찬양", "새가족", "중보기도"],
  },
};

export const MOCK_FAMILY: Record<string, FamilyMember[]> = {
  "m-001": [
    {
      id: "f-001",
      memberId: "spouse-001",
      relation: "SPOUSE",
      isHead: true,
      name: "김철수",
      sex: "M",
      birthDate: "1979-03-20",
      age: 47,
      phone: "010-1111-2222",
      status: "ACTIVE",
      faithStage: "MINISTER",
      office: "DEACON",
      groupNote: "찬양팀 리더",
      avatarGrad: 2,
      initial: "김",
      isLinked: true,
    },
    {
      id: "f-002",
      memberId: "child-001",
      relation: "CHILD",
      isHead: false,
      name: "김다연",
      sex: "F",
      birthDate: "2011-11-08",
      age: 15,
      status: "ACTIVE",
      groupNote: "중등부",
      avatarGrad: 7,
      initial: "김",
      isLinked: true,
    },
    {
      id: "f-003",
      memberId: "child-002",
      relation: "CHILD",
      isHead: false,
      name: "김지훈",
      sex: "M",
      birthDate: "2015-05-22",
      age: 11,
      status: "ACTIVE",
      groupNote: "초등부",
      avatarGrad: 4,
      initial: "김",
      isLinked: true,
    },
    {
      id: "f-004",
      externalName: "이영자",
      relation: "PARENT",
      isHead: false,
      name: "이영자",
      sex: "F",
      birthDate: "1955-02-10",
      age: 70,
      phone: "010-5555-6666",
      groupNote: "친정 어머니 · 다른 교회 출석",
      avatarGrad: 6,
      initial: "?",
      isLinked: false,
    },
  ],
};

export const MOCK_SERVICES: Record<
  string,
  { active: ServiceAssignment[]; past: ServiceAssignment[]; tags: string[]; trainings: TrainingRecord[] }
> = {
  "m-001": {
    active: [
      {
        id: "s-001",
        department: "주일학교 초등부",
        team: undefined,
        role: "1학년 담임 교사",
        startedAt: "2022-03-06",
        schedule: "주일 9:30 ~ 11:00, 교육관 201호",
        isActive: true,
      },
      {
        id: "s-002",
        department: "찬양팀 (세컨드)",
        role: "피아노",
        startedAt: "2020-09-13",
        schedule: "2부 예배 · 월 2~3회",
        isActive: true,
      },
    ],
    past: [
      {
        id: "s-101",
        department: "새가족부 안내팀",
        role: "팀원",
        startedAt: "2019-03-01",
        endedAt: "2021-12-31",
        isActive: false,
      },
      {
        id: "s-102",
        department: "중보기도팀",
        role: "팀원",
        startedAt: "2018-09-01",
        endedAt: "2020-06-30",
        isActive: false,
      },
      {
        id: "s-103",
        department: "주일학교 영아부",
        role: "보조교사",
        startedAt: "2018-06-01",
        endedAt: "2019-02-28",
        isActive: false,
      },
    ],
    tags: ["피아노", "교사", "성경공부 인도", "중보기도"],
    trainings: [
      { id: "t-001", year: "2024", programName: "사역훈련 1기", completedAt: "2024-11-17" },
      { id: "t-002", year: "2022", programName: "제자훈련 (1년 과정)", completedAt: "2022-12-04" },
      { id: "t-003", year: "2019", programName: "성경대학 (2년)", completedAt: "2019-06-30" },
      { id: "t-004", year: "2018", programName: "새가족반", completedAt: "2018-04-22" },
    ],
  },
};

export const MOCK_EVENTS: Record<string, MemberEvent[]> = {
  "m-001": [
    {
      id: "e-001",
      type: "STAGE_PROMOTION_CANDIDATE",
      occurredAt: "2026-04-15 09:20",
      title: "사역훈련 수료 → Lv5 승급 후보로 전환",
      detail: "시스템 자동 판정 · 담당: 한원철 목사 확정 대기",
      actor: "시스템",
      badgeLabel: "승급 후보",
      dotColor: "bg-[#3f74c7]",
      ringColor: "ring-[#edf4ff]",
      badgeColor: "bg-orange-50 text-orange-700",
    },
    {
      id: "e-002",
      type: "TRAINING_COMPLETED",
      occurredAt: "2026-04-15 09:18",
      title: "사역훈련 1기 수료 기록 추가",
      detail: "작성자: 한원철 목사",
      actor: "한원철 목사",
      badgeLabel: "교육",
      dotColor: "bg-emerald-500",
      ringColor: "ring-emerald-50",
      badgeColor: "bg-emerald-50 text-emerald-700",
    },
    {
      id: "e-003",
      type: "ADDRESS_CHANGED",
      occurredAt: "2026-04-02 14:51",
      title: "주소 변경",
      diff: {
        before: "서울시 송파구 올림픽로 88 ...",
        after: "서울시 강남구 테헤란로 123, 101동 1502호",
      },
      actor: "한원철 목사",
      badgeLabel: "주소",
      dotColor: "bg-sky-500",
      ringColor: "ring-sky-50",
      badgeColor: "bg-sky-50 text-sky-700",
    },
    {
      id: "e-004",
      type: "SERVICE_ASSIGNED",
      occurredAt: "2026-02-11 19:33",
      title: "찬양팀(세컨드) 피아노 봉사 배정",
      actor: "한원철 목사",
      badgeLabel: "봉사",
      dotColor: "bg-purple-500",
      ringColor: "ring-purple-50",
      badgeColor: "bg-purple-50 text-purple-700",
    },
    {
      id: "e-005",
      type: "STAGE_CHANGED",
      occurredAt: "2025-12-21 10:05",
      title: "신앙 레벨 변경: 양육교인 → 제자",
      detail: "사유: 제자훈련 1년차 수료 확인 · 작성자: 한원철 목사",
      actor: "한원철 목사",
      badgeLabel: "레벨",
      dotColor: "bg-[#3f74c7]",
      ringColor: "ring-[#edf4ff]",
      badgeColor: "bg-[#edf4ff] text-[#2d5da8]",
    },
    {
      id: "e-006",
      type: "OFFICE_CHANGED",
      occurredAt: "2025-12-21 10:02",
      title: "직분 변경: 평신도 → 서리집사",
      detail: "임직일 2021-01-03 (소급 기록) · 작성자: 한원철 목사",
      actor: "한원철 목사",
      badgeLabel: "직분",
      dotColor: "bg-amber-500",
      ringColor: "ring-amber-50",
      badgeColor: "bg-amber-50 text-amber-700",
    },
    {
      id: "e-007",
      type: "REGISTERED",
      occurredAt: "2018-03-11 11:40",
      title: "교적 등록 (새가족)",
      detail: "이전 교회: — · 초기 상태: 새가족 (Lv1)",
      actor: "한원철 목사",
      badgeLabel: "등록",
      dotColor: "bg-blue-500",
      ringColor: "ring-blue-50",
      badgeColor: "bg-blue-50 text-blue-700",
    },
  ],
};

export const MOCK_ATTENDANCE: Record<string, AttendanceWeek[]> = {
  "m-001": [
    { date: "4/5", status: "ATTEND" },
    { date: "4/12", status: "ATTEND" },
    { date: "4/19", status: "ONLINE" },
    { date: "4/26", status: null },
  ],
};

export const MOCK_CELLS = [
  { id: "c-1", label: "1구역 · 요한셀" },
  { id: "c-2", label: "2구역 · 바울셀" },
  { id: "c-3", label: "3구역 · 마가셀" },
  { id: "c-4", label: "4구역 · 누가셀" },
  { id: "c-5", label: "5구역 · 베드로셀" },
];

export const MOCK_SUMMARY = {
  total: 487,
  active: 421,
  newcomer: 18,
  resting: 42,
  suggestionCount: 7,
};
